CREATE TABLE INVENTORY_SEARCH_TYPE(
ID INT NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR(255) NOT NULL,
ACTIVE INT NOT NULL,
PRIMARY KEY (ID));

    INSERT INTO INVENTORY_SEARCH_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'Gel all',1);
    INSERT INTO INVENTORY_SEARCH_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'Get all active',1);
    INSERT INTO INVENTORY_SEARCH_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'Get all finnished',1);
    INSERT INTO INVENTORY_SEARCH_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'Get all new',1);
    INSERT INTO INVENTORY_SEARCH_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'Get all cancelled',1);