CREATE TABLE INVENTORY_EVENT_TYPE(
ID INT NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR(255) NOT NULL,
ACTIVE INT NOT NULL,
PRIMARY KEY (ID));


    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'INVENTORY CREATED',1);
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'INVENTORY STARTED',1);
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'INVENTORY ENDED',1);
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'INVENTORY CANCELLED',1);
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'PRODUCT ADDED',1);
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'DUPLICATE SCANNED',1);
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'INVENTORY PERSON ASSIGNED',1);   
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'INVENTORY PERSON REMOVED',1);
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'REPORT CREATED',1);