CREATE TABLE INVENTORY_STATUS(
ID INT NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR(255) NOT NULL,
ACTIVE INT NOT NULL,
PRIMARY KEY (ID));


    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'NEW',1);
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'ACTIVE',1);
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'COMPLETE',1);
    INSERT INTO INVENTORY_STATUS(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'CANCELLED',1);