CREATE TABLE OWNER(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
LOCATION VARCHAR(255) NOT NULL,
ACTIVE INT NOT NULL,
PRIMARY KEY (ID)
);



    INSERT INTO OWNER(ID,NAME,LOCATION,ACTIVE) VALUES (NULL,'OWNER 1', 'Location 1',1);
    INSERT INTO OWNER(ID,NAME,LOCATION,ACTIVE) VALUES (NULL,'OWNER 2', 'Location 2',1);
