CREATE TABLE PRODUCT_SEARCH_TYPE(
ID INT NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR(255) NOT NULL,
ACTIVE INT NOT NULL,
PRIMARY KEY (ID));

    INSERT INTO PRODUCT_SEARCH_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'Get all products',1);
    INSERT INTO PRODUCT_SEARCH_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'Get all active products',1);
    INSERT INTO PRODUCT_SEARCH_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'Get all products tied to my zone',1);
    INSERT INTO PRODUCT_SEARCH_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'Get all moved products',1);