CREATE TABLE PRODUCT(
ID INT NOT NULL AUTO_INCREMENT,
OWNER_ID INT NOT NULL,
PRODUCT_TYPE_ID INT NOT NULL,
PRODUCT_STATUS_ID INT NOT NULL,
ZONE_ID INT NOT NULL,
DESCRIPTION VARCHAR(255) NULL,
PRIMARY KEY (ID),
FOREIGN KEY (OWNER_ID) REFERENCES OWNER(ID),
FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE(ID),
FOREIGN KEY (PRODUCT_STATUS_ID) REFERENCES PRODUCT_STATUS(ID),
FOREIGN KEY (ZONE_ID) REFERENCES ZONE(ID)
);     