CREATE TABLE PRODUCT_TYPE(
ID INT NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR(255) NOT NULL,
ACTIVE INT NOT NULL,
PRIMARY KEY (ID)
)







    INSERT INTO PRODUCT_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'BOX',1);
    INSERT INTO PRODUCT_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'PALLET',1);
    INSERT INTO PRODUCT_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'BOTTLE',1);
    INSERT INTO PRODUCT_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'CAN',1);
    INSERT INTO PRODUCT_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'OTHER',1);