CREATE TABLE USER_HISTORY_TYPE(
ID INT NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR(255) NOT NULL,
ACTIVE INT NOT NULL,
PRIMARY KEY (ID)
);


    INSERT INTO USER_HISTORY_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'SUCCESSFUL LOG ON',1);
    INSERT INTO USER_HISTORY_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'UNSUCCESSFUL LOG ON',1);
    INSERT INTO USER_HISTORY_TYPE(ID,DESCRIPTION,ACTIVE) VALUES (NULL,'PASSWORD CHANGED',1);