CREATE TABLE USER_HISTORY(
ID INT NOT NULL AUTO_INCREMENT,
USER_ID INT NULL,
EVENT_DATE TIMESTAMP NULL,
DESCRIPTION VARCHAR(255) NULL,
USER_HISTORY_TYPE_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (USER_HISTORY_TYPE_ID) REFERENCES USER_HISTORY_TYPE(ID)
);   