CREATE TABLE USER(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    ZONE_ID INT NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    HASH VARCHAR(255) NOT NULL,
    SALT VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ZONE_ID) REFERENCES ZONE(ID)
);