CREATE TABLE ZONE(
ID INT NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR(255) NOT NULL,
PARENT_ZONE_ID INT NULL,
ACTIVE INT NOT NULL,
PRIMARY KEY (ID));


INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "WORLD", NULL, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1", 1, 1)  ;
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 2", 1, 1) ;
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 3", 1, 1) ;
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 3", 1, 1) ;
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 1", 2, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 2", 2, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 3", 2, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 4", 2, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 2 SHELF 1", 3, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 1 RACK 1", 6, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 2 RACK 1", 7, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 3 RACK 1", 8, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 4 RACK 1", 9, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 1 RACK 2", 6, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 2 RACK 2", 7, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 3 RACK 2", 8, 1);
INSERT INTO ZONE(ID, DESCRIPTION, PARENT_ZONE_ID, ACTIVE) VALUES (NULL, "ZONE 1 SHELF 4 RACK 2", 9, 1);